OnlineShop/Models/Favorite.cs
namespace OnlineShop.Models
{
    public class Favorite
    {
        public Guid Id { get; set; }
        public string UserId { get; set; }
        public List<Product> Items { get; set; }
    }
}

OnlineShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Interfaces;

namespace OnlineShop.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductsRepository _productsRepository;
        private readonly ICartsRepository _cartsRepository;

        public CartController(IProductsRepository productsRepository, ICartsRepository cartsRepository)
        {
            _productsRepository = productsRepository;
            _cartsRepository = cartsRepository;
        }

        public IActionResult Index()
        {
            var cart = _cartsRepository.TryGetByUserId(Constants.UserId);

            return View(cart);
        }

        public IActionResult Add(int productId)
        {
            var product = _productsRepository.TryGetById(productId);

            if (product != null)
            {
                _cartsRepository.Add(product, Constants.UserId);
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Subtract(int productId)
        {
            _cartsRepository.Subtract(productId, Constants.UserId);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Clear()
        {
            _cartsRepository.Clear(Constants.UserId);

            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineShop/Controllers/FavoriteController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Interfaces;

namespace OnlineShop.Controllers
{
    public class FavoriteController : Controller
    {
        private readonly IProductsRepository _productsRepository;
        private readonly IFavoritesRepository _favoritesRepository;
        public FavoriteController(IProductsRepository productsRepository, IFavoritesRepository favoritesRepository)
        {
            _productsRepository = productsRepository;
            _favoritesRepository = favoritesRepository;
        }

        public IActionResult Index()
        {
            var favorites = _favoritesRepository.TryGetByUserId(Constants.UserId);
            return View(favorites);
        }
        public IActionResult Add(int productId)
        {
            var product = _productsRepository.TryGetById(productId);

            if (product != null)
            {
                _favoritesRepository.Add(product, Constants.UserId);
            }

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int productId)
        {
            _favoritesRepository.Delete(productId, Constants.UserId);

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Clear()
        {
            _favoritesRepository.Clear(Constants.UserId);

            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineShop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Models;
using OnlineShop.Interfaces;

namespace OnlineShop.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductsRepository _productsRepository;

        public ProductController(IProductsRepository productsRepository)
        {
            _productsRepository = productsRepository;
        }
        public IActionResult Index(int id)
        {
            var product = _productsRepository.TryGetById(id);

            return View(product);
        }
    }
}

OnlineShop/Views/Favorite/Index.cshtml
@model Favorite

@{
    ViewData["Title"] = "Избранное";
}

<div class="text-center text-uppercase text-success mb-5 mt-5">
    <h2 class="row-title">Избранное</h2>
</div>

@if (Model != null && Model.Items?.Count > 0)
{
    <div class="row justify-content-center mt-3">
        @foreach (var product in Model.Items)
        {
            <div class="col-3 mb-3">
                <div class="card shadow">
                    <img class="card-img-top" src=@product.PhotoPath alt="...">
                    <div class="card-body text-center">
                        <a class="text-success"
                           asp-controller="Product"
                           asp-action="Index"
                           asp-route-id="@product.Id">
                            <h5>@product.Name</h5>
                        </a>
                        <h2 class="text-danger">@product.Cost.ToString("c")</h2>
                        <hr />
                        <h6>@product.Description</h6>
                        <hr />
                        <a class="btn btn-success"
                           asp-controller="Cart"
                           asp-action="Add"
                           asp-route-productId="@product.Id">
                            Добавить в корзину
                        </a>
                        <a class="btn btn-outline-danger mt-3"
                           asp-controller="Favorite"
                           asp-action="Delete"
                           asp-route-productId="@product.Id">
                            Убрать из избранного
                        </a>
                    </div>
                </div>
            </div>
        }

        <div class="text-center mt-5">
            <a class="btn btn-outline-danger"
               asp-controller="Favorite"
               asp-action="Clear">
                Очистить список избранного
            </a>
        </div>
    </div>
}
else
{
    <div class="text-center">
        <h2 class="row-title">В списке избранного нет товаров!</h2>
    </div>

}

<div class="text-center m-5">
    <a class="btn btn-outline-success"
       asp-controller="Home"
       asp-action="Index">
        Продолжить покупки
    </a>
</div>